name: CI

on:
  push:
    branches: master

jobs:

  test-github-hosted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - &test-step
        shell: bash
        run: |
          set -euo pipefail
          set -x
          python3 main.py 1
          python3 main.py 1 2
          python3 main.py 1 2 3

  test-self-hosted:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v6
      - *test-step
